name: Publish to NPM
on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    name: Publish to NPM
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Add hashes to package.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm ci --ignore-scripts
          node lib/prebuild.mjs snapshot
          npm pkg get prebuild

      - name: Publish to NPM
        run: npm publish --provenance --access public
